
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        <li> Equipo |  PG  |  PP  |  PE </li>
        <?php foreach ($equipos as $equipo) { ?>
            <li> <?= $equipo->nombre ?> | <?= $equipo->partidos_ganados ?> | <?= $equipo->partidos_perdidos ?> | <?= $equipo->partidos_empatados ?></li>
        <?php } ?>
    </ul>

</body>
</html>
